import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Inter } from 'next/font/google'
import './globals.css'
import { StoreProvider } from '@/lib/StoreProvider'
import HeaderLayout from '../appLayout/header'
import FooterLayout from '../appLayout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <HeaderLayout />
            <main>{children}</main>
            <FooterLayout />
          </AppRouterCacheProvider>
        </body>
      </html>
    </StoreProvider>
  )
}
