import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import { Noto_Sans_TC } from 'next/font/google'
import './globals.css'
import './layout.scss'
import { StoreProvider } from '@/lib/StoreProvider'
import HeaderLayout from '../appLayout/header'
import FooterLayout from '../appLayout/footer'
import { ReactElement } from 'react'

const inter = Noto_Sans_TC({
  weight: ['400', '600'],
  style: ['normal'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactElement
  params: { lang: string }
}

export default function RootLayout({
  children,
  params: { lang },
}: RootLayoutProps) {
  const messages = useMessages()

  return (
    <StoreProvider>
      <html lang={lang}>
        <NextIntlClientProvider locale={lang} messages={messages}>
          <body className={inter.className}>
            <AppRouterCacheProvider>
              <HeaderLayout />
              <main>{children}</main>
              <FooterLayout lang={lang} />
            </AppRouterCacheProvider>
          </body>
        </NextIntlClientProvider>
      </html>
    </StoreProvider>
  )
}
