import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Inter } from 'next/font/google'
import './globals.css'
import './layout.scss'
import { StoreProvider } from '@/lib/StoreProvider'
import HeaderLayout from '../appLayout/header'
import FooterLayout from '../appLayout/footer'
import { ReactElement } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface RootLayoutProps { 
  children: ReactElement
  params: { lang: string }
}

export default async function RootLayout({
  children,
  params: { lang },
}: RootLayoutProps) {

  return (
    <StoreProvider>
      <html lang={lang}>
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <HeaderLayout />
            <main>{children}</main>
            <FooterLayout lang={lang} />
          </AppRouterCacheProvider>
        </body>
      </html>
    </StoreProvider>
  )
}
